sudo: required
services:
    - docker

before-install:
    - docker build -t subbaraocherukuri/docker-react -f Dockerfile.dev .

services:
    - docker run -e CI=true subbaraocherukuri/docker-react npm run test
