language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t subbaraocherukuri/docker-react -f Dockerfile.dev .

services:
    - docker run -e CI=true subbaraocherukuri/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-1-986261949459"
    bucket_path: "docker-react"
    on:
        branch: master
    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY